### ISSUE TITLE
results produced by this repository are different from the original eval code

### ISSUE THREAD

**Issue by XYZ-qiyh** [cdcseacave/DTUeval#2]
Hi, @cdcseacave . Thanks for your improvement for DTU evaluation code!
I'm using this repository for my MVS evaluation. But I found the results produced by this repository 
are slightly bigger than the original eval code.
For example, the evaluation results of DTU scan1 are as follows.

![1](https://user-images.githubusercontent.com/45621782/76828296-96d3d880-685b-11ea-8127-e237f11e1522.png)

Looking forward to your reply.

**Comment by cdcseacave** [comment]
in my opinion the original code is incorrect, it has some bug, which I corrected; and so it is normal you get different results

**Comment by XYZ-qiyh** [comment]
Thanks for your reply. @cdcseacave 
Maybe the bugs in original code are the ones mentioned in your `README` file ? Or something else?
https://github.com/cdcseacave/DTUeval/blob/e3d6bdcc1783086f320b5363808654c10c265439/MeshSupSamp_web/PointsDist/PointsDist.cpp#L53-L56


`fix MaxDistCP to compute the true score, regardless of the set MaxDist value`
But I found in `PointsDist.cpp`, the MaxDist value is considered.
